version: 2.1

commands:
    destroy-env:
      description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
      parameters:
          workflow_id:
            type: string
          event:
            type: string        
      steps:
        - run:
            name: Destroy environment << parameters.workflow_id >>
            when: << parameters.event >>
            command: |
              echo "Destroying environment: << parameters.workflow_id >>"
              aws s3 rm s3://udapeople-<< parameters.workflow_id >> --recursive
              aws cloudformation delete-stack --stack-name "udapeople-backend-<< parameters.workflow_id >>"
              aws cloudformation delete-stack --stack-name "udapeople-frontend-<< parameters.workflow_id >>"
              
    
jobs:

    build_frontend:
      
      docker:
          - image: circleci/node:13.8.0
      steps:
          - checkout
          - restore_cache:
              keys: [frontend-build]
          - run:
              name: Build front-end
              command: |
                cd frontend
                npm install
                npm run build
          - save_cache:
              paths: [frontend/node_modules]
              key: frontend-build

    build_backend:
      
      docker:
          - image: circleci/node:13.8.0
      steps:
          - checkout
          - restore_cache:
              keys: [backend-build]
          - run:
              name: Build back-end
              command: |
                cd backend
                npm install
                npm run build
          - save_cache:
              paths: [backend/node_modules]
              key: backend-build

    test_frontend:

      docker:
          - image: circleci/node:13.8.0
      steps:
          - checkout
          - restore_cache:
              keys: [frontend-build]
          - run:
              name: Run Frontend Test
              command: |
                cd frontend
                npm install
                npm run test

    test_backend:

      docker:
          - image: circleci/node:13.8.0
      steps:
          - checkout
          - restore_cache:
              keys: [backend-build]
          - run:
              name: Scan Backend
              command: |
                cd backend
                npm install
                npm run test

    scan_frontend: 

      docker:
          - image: circleci/node:13.8.0
      steps:
          - checkout
          - restore_cache:
                keys: [frontend-build]
          - run:
                name: Scan frontend
                command: |
                  cd frontend
                  npm install
                  npm audit fix --audit-level=critical --force

    scan_backend: 

      docker:
          - image: circleci/node:13.8.0
      steps:
          - checkout
          - restore_cache:
                keys: [backend-build]
          - run:
                name: Scan Backend
                command: |
                  cd backend
                  npm install
                  npm audit fix --audit-level=critical --force

    deploy-infrastructure:

      docker: 
          - image: amazon/aws-cli
      steps:
          - checkout
          - run:
              name: Install tar and gz package
              command: |
                yum install -y tar gzip
          - run:
              name: Ensure backend infrastructure exists
              command: |
                aws cloudformation deploy \
                  --template-file .circleci/files/backend.yml \
                  --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
                  --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
                  --tags project=udapeople 
          - run:
              name: Ensure frontend infrastructure exists
              command: |
                aws cloudformation deploy \
                  --template-file .circleci/files/frontend.yml \
                  --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
                  --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
                  --tags project=udapeople
          - run:
              name: Add the EC2 instance IP to the Ansible inventory
              command: |
                aws ec2 describe-instances \
                  --query 'Reservations[*].Instances[*].PublicIpAddress' \
                  --output text >> ./.circleci/ansible/inventory.txt
                cat ./.circleci/ansible/inventory.txt
          - persist_to_workspace:
              root: ~/
              paths:
                - ./.circleci/ansible/inventory.txt
          - destroy-env:
              workflow_id: "{CIRCLE_WORKFLOW_ID:0:7}"
              event: on_fail

    configure-infrastructure:

        docker: 
            - image: python:3.7-alpine3.11
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints: ["87:ea:4b:b3:be:67:e5:c4:d3:d1:98:ff:88:1c:1b:ac"]
            - attach_workspace: 
                at: ~/
            - run:
                name: Install dependencies
                command: |
                  yum install -y tar gzip
                  apk add --update ansible
                  pip install aws cli
            - run:
                name: Configure server
                command: |
                  cd .circleci/ansible
                  ansible-playbook -i inventory.txt configure-sever.yml


          



workflows:

  default:
    
    jobs:
      - build_frontend
      - build_backend
      - test_frontend:
          requires: 
            - build_frontend
      - test_backend:
          requires:
            - build_backend
      - scan_frontend:
          requires: 
            - build_frontend
      - scan_backend:
          requires:
            - build_backend
      - deploy-infrastructure:
          requires: [test_frontend, test_backend, scan_frontend, scan_backend]
      - configure-infrastructure:
          requires: [deploy-infrastructure]
